name: imcalledandy
favicon: null
layout_spectrum: 0.28544583544135094
typography_spectrum: 0.4907
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9375
  lightness: 0.8385354101192206
  saturation: 0.75
  rhythmicContrast: 0.4671624884940684
purpose: []
